### ISSUE TITLE
Models and their Attributes

### ISSUE THREAD

**Issue by asquare14** [BearWithMe088/LearnIT-Girl#4]
#### User Model :
- [ ] - Name
- [ ] - Email
- [ ] - Password
- [ ] - Bio
- [ ] - Location
- [ ] - Age
- [ ] - Sex
- [ ] - Photo

#### Tasks-

- [ ] A page for signup. 
- [ ] A page for login.
- [ ] After login, display profile page that can be edited.

#### Portal Model

- For now does nothing.
